services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_DATABASE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
