#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Prettierとlintチェックを実行中..."
npx lint-staged

echo "🔎 フロントエンドの型チェックを実行中..."
cd frontend && npm run typecheck

echo "🔎 バックエンドの型チェックを実行中..."
cd ../backend && npm run typecheck
