/* eslint-disable max-lines */
export const jaJP = {
  locale: "ja-JP",
  socialButtonsBlockButton: "{{provider|titleize}}でサインイン",
  dividerText: "または",
  formFieldLabel__emailAddress: "メールアドレス",
  formFieldLabel__emailAddresses: "メールアドレス",
  formFieldLabel__phoneNumber: "電話番号",
  formFieldLabel__username: "ユーザーネーム",
  formFieldLabel__emailAddress_username: "メールアドレスまたはユーザーネーム",
  formFieldLabel__password: "パスワード",
  formFieldLabel__currentPassword: "現在のパスワード",
  formFieldLabel__newPassword: "新しいパスワード",
  formFieldLabel__confirmPassword: "パスワードを確認",
  formFieldLabel__signOutOfOtherSessions: "他のすべてのデバイスからサインアウト",
  formFieldLabel__firstName: "名",
  formFieldLabel__lastName: "姓",
  formFieldLabel__backupCode: "バックアップコード",
  formFieldLabel__organizationName: "組織名",
  formFieldLabel__organizationSlug: "組織のスラッグ",
  formFieldLabel__organizationDomain: "組織のドメイン",
  formFieldLabel__organizationDomainEmailAddress: "メールアドレスで確認",
  formFieldLabel__organizationDomainEmailAddressDescription:
    "確認のため、このドメインのメールアドレスでメールを受信してください。",
  formFieldLabel__organizationDomainDeletePending: "保留中の招待と提案を削除",
  formFieldLabel__confirmDeletion: "確認",
  formFieldLabel__role: "役割",
  formFieldInputPlaceholder__emailAddress: "",
  formFieldInputPlaceholder__emailAddresses: "スペースまたはカンマで区切って入力",
  formFieldInputPlaceholder__phoneNumber: "",
  formFieldInputPlaceholder__username: "",
  formFieldInputPlaceholder__emailAddress_username: "",
  formFieldInputPlaceholder__password: "",
  formFieldInputPlaceholder__firstName: "",
  formFieldInputPlaceholder__lastName: "",
  formFieldInputPlaceholder__backupCode: "",
  formFieldInputPlaceholder__organizationName: "",
  formFieldInputPlaceholder__organizationSlug: "",
  formFieldInputPlaceholder__organizationDomain: "",
  formFieldInputPlaceholder__organizationDomainEmailAddress: "",
  formFieldError__notMatchingPasswords: "パスワードが一致しません",
  formFieldError__matchingPasswords: "現在のパスワードと同じです",
  formFieldError__verificationLinkExpired:
    "確認リンクの有効期限が切れています。新しいリンクをリクエストしてください。",
  formFieldAction__forgotPassword: "パスワードを忘れた場合",
  formFieldHintText__optional: "任意",
  formFieldHintText__slug:
    "スラッグは、URLセーフな識別子です。通常は小文字で、単語はダッシュで区切られます。",
  formButtonPrimary: "続ける",
  signInEnterPasswordTitle: "パスワードを入力",
  backButton: "戻る",
  footerActionLink__useAnotherMethod: "別の方法を使用",
  badge__primary: "プライマリ",
  badge__thisDevice: "このデバイス",
  badge__userDevice: "ユーザーデバイス",
  badge__otherImpersonatorDevice: "他のなりすましデバイス",
  badge__default: "デフォルト",
  badge__unverified: "未確認",
  badge__requiresAction: "アクションが必要",
  badge__you: "あなた",
  footerPageLink__help: "ヘルプ",
  footerPageLink__privacy: "プライバシー",
  footerPageLink__terms: "利用規約",
  paginationButton__previous: "前へ",
  paginationButton__next: "次へ",
  paginationRowText__displaying: "表示中",
  paginationRowText__of: "/",
  membershipRole__admin: "管理者",
  membershipRole__basicMember: "メンバー",
  membershipRole__guestMember: "ゲスト",
  signUp: {
    start: {
      title: "アカウントを作成",
      subtitle: "{{applicationName}}への登録を開始",
      actionText: "すでにアカウントをお持ちですか？",
      actionLink: "サインイン",
    },
    emailLink: {
      title: "メールを確認",
      subtitle: "{{applicationName}}への登録を続ける",
      formTitle: "メール確認リンク",
      formSubtitle: "登録メールアドレスに送信された確認リンクを使用",
      resendButton: "確認リンクを再送信",
      verified: {
        title: "サインアップ成功",
      },
      loading: {
        title: "サインアップ中...",
      },
      verifiedSwitchTab: {
        title: "メールアドレスの確認が完了しました",
        subtitle: "新しく開いたタブに戻って続行",
        subtitleNewTab: "このタブに戻って続行",
      },
    },
    emailCode: {
      title: "メールを確認",
      subtitle: "{{applicationName}}への登録を続ける",
      formTitle: "確認コード",
      formSubtitle: "登録メールアドレスに送信された確認コードを入力",
      resendButton: "確認コードを再送信",
    },
    phoneCode: {
      title: "電話番号を確認",
      subtitle: "{{applicationName}}への登録を続ける",
      formTitle: "確認コード",
      formSubtitle: "登録電話番号に送信された確認コードを入力",
      resendButton: "確認コードを再送信",
    },
    continue: {
      title: "フォームに入力",
      subtitle: "{{applicationName}}への登録を続ける",
      actionText: "別のアカウントを使用",
      actionLink: "サインアップ",
    },
    formButtonPrimary__continue: "続ける",
    formButtonPrimary__finish: "完了",
    formButtonReset: "キャンセル",
  },
  signIn: {
    start: {
      title: "サインイン",
      subtitle: "{{applicationName}}へのサインインを続ける",
      actionText: "アカウントをお持ちでない場合",
      actionLink: "サインアップ",
      actionLink__use_email: "メールアドレスを使用",
      actionLink__use_phone: "電話番号を使用",
      actionLink__use_username: "ユーザーネームを使用",
      actionLink__use_email_username: "メールアドレスまたはユーザーネームを使用",
    },
    password: {
      title: "パスワードを入力",
      subtitle: "{{applicationName}}へのサインインを続ける",
      actionLink: "パスワードを忘れた場合",
    },
    passwordPwned: {
      title: "パスワードが流出しています",
      subtitle__update_password: "アカウントを保護するため、パスワードを更新してください",
      subtitle__sign_in: "サインインを続ける",
      actionButton__update_password: "パスワードを更新",
      actionButton__continue: "このまま続ける",
    },
    forgotPasswordTitle: "パスワードリセット",
    forgotPasswordSubtitle: "パスワードをリセットするメールアドレスを入力",
    forgotPasswordAction: "パスワードを覚えていますか？",
    forgotPasswordActionLink: "サインイン",
    resetPasswordTitle: "新しいパスワードを設定",
    resetPasswordSubtitle: "アカウント用の新しいパスワードを入力",
    resetPasswordSuccessTitle: "パスワードをリセットしました",
    resetPasswordSuccessDescription: "新しいパスワードでサインインできます",
    resetPasswordMfa: {
      detailsLabel: "パスワードをリセットする前に、本人確認が必要です。",
    },
    emailCode: {
      title: "メールを確認",
      subtitle: "{{applicationName}}へのサインインを続ける",
      formTitle: "確認コード",
      formSubtitle: "メールアドレスに送信された確認コードを入力",
      resendButton: "確認コードを再送信",
    },
    emailLink: {
      title: "メールを確認",
      subtitle: "{{applicationName}}へのサインインを続ける",
      formTitle: "メール確認リンク",
      formSubtitle: "メールに送信された確認リンクを使用",
      resendButton: "確認リンクを再送信",
      unusedTab: {
        title: "このタブは閉じて構いません",
      },
      verified: {
        title: "サインイン成功",
        subtitle: "間もなくリダイレクトされます",
      },
      verifiedSwitchTab: {
        subtitle: "元のタブに戻って続行",
        titleNewTab: "別のタブでサインインしました",
        subtitleNewTab: "このタブに戻って続行",
      },
      loading: {
        title: "サインイン中...",
        subtitle: "間もなくリダイレクトされます",
      },
      failed: {
        title: "この確認リンクは無効です",
        subtitle: "元のタブに戻って続行してください。",
      },
      expired: {
        title: "この確認リンクは期限切れです",
        subtitle: "元のタブに戻って続行してください。",
      },
    },
    phoneCode: {
      title: "電話番号を確認",
      subtitle: "{{applicationName}}へのサインインを続ける",
      formTitle: "確認コード",
      formSubtitle: "電話番号に送信された確認コードを入力",
      resendButton: "確認コードを再送信",
    },
    phoneCodeMfa: {
      title: "2段階認証",
      subtitle: "続行するには、電話番号に送信された確認コードを入力してください",
      formTitle: "確認コード",
      formSubtitle: "電話番号に送信された確認コードを入力",
      resendButton: "確認コードを再送信",
    },
    totpMfa: {
      title: "2段階認証",
      subtitle: "続行するには、認証アプリの確認コードを入力してください",
      formTitle: "確認コード",
      formSubtitle: "認証アプリの確認コードを入力",
    },
    backupCodeMfa: {
      title: "バックアップコードを入力",
      subtitle: "続行するには、バックアップコードの1つを入力してください",
      formTitle: "",
      formSubtitle: "",
    },
    alternativeMethods: {
      title: "その他の方法でサインイン",
      actionLink: "ヘルプ",
      blockButton__emailLink: "{{identifier}}にメールリンクを送信",
      blockButton__emailCode: "{{identifier}}に確認コードを送信",
      blockButton__phoneCode: "{{identifier}}にSMSコードを送信",
      blockButton__password: "パスワードでサインイン",
      blockButton__totp: "認証アプリを使用",
      blockButton__backupCode: "バックアップコードを使用",
      getHelp: {
        title: "ヘルプ",
        content:
          "アカウントへのアクセスに問題がある場合は、メールでお問い合わせください。できるだけ早くお手伝いいたします。",
        blockButton__emailSupport: "サポートにメール",
      },
    },
    noAvailableMethods: {
      title: "サインインできません",
      subtitle: "エラーが発生しました",
      message: "サインインを続行できません。利用可能な認証方法がありません。",
    },
  },
  userProfile: {
    mobileButton__menu: "メニュー",
    formButtonPrimary__continue: "続ける",
    formButtonPrimary__finish: "完了",
    formButtonReset: "キャンセル",
    navbar: {
      title: "アカウント",
      description: "アカウント情報を管理",
      account: "アカウント",
      security: "セキュリティ",
    },
    header: {
      title: "アカウント",
      subtitle: "アカウント情報とセキュリティを管理",
    },
    profileSection: {
      title: "プロフィール",
    },
    usernameSection: {
      title: "ユーザーネーム",
      primaryButton__changeUsername: "ユーザーネームを変更",
      primaryButton__setUsername: "ユーザーネームを設定",
    },
    emailAddressesSection: {
      title: "メールアドレス",
      primaryButton: "メールアドレスを追加",
      detailsTitle__primary: "プライマリメールアドレス",
      detailsSubtitle__primary: "このメールアドレスはプライマリメールアドレスです",
      detailsAction__primary: "確認を完了",
      detailsTitle__nonPrimary: "プライマリに設定",
      detailsSubtitle__nonPrimary:
        "このメールアドレスをプライマリにして、アカウント関連の通知を受け取る",
      detailsAction__nonPrimary: "プライマリに設定",
      detailsTitle__unverified: "メールアドレスを確認",
      detailsSubtitle__unverified: "このメールアドレスの確認を完了して、すべての機能にアクセス",
      detailsAction__unverified: "確認メールを再送信",
      destructiveActionTitle: "メールアドレスを削除",
      destructiveActionSubtitle: "このメールアドレスをアカウントから削除",
      destructiveAction: "削除",
    },
    phoneNumbersSection: {
      title: "電話番号",
      primaryButton: "電話番号を追加",
      detailsTitle__primary: "プライマリ電話番号",
      detailsSubtitle__primary: "この電話番号はプライマリ電話番号です",
      detailsAction__primary: "確認を完了",
      detailsTitle__nonPrimary: "プライマリに設定",
      detailsSubtitle__nonPrimary: "この電話番号をプライマリにして、アカウント関連の通知を受け取る",
      detailsAction__nonPrimary: "プライマリに設定",
      detailsTitle__unverified: "電話番号を確認",
      detailsSubtitle__unverified: "この電話番号の確認を完了して、すべての機能にアクセス",
      detailsAction__unverified: "確認コードを再送信",
      destructiveActionTitle: "電話番号を削除",
      destructiveActionSubtitle: "この電話番号をアカウントから削除",
      destructiveAction: "削除",
    },
    connectedAccountsSection: {
      title: "接続されたアカウント",
      primaryButton: "アカウントを接続",
      title__conectionFailed: "接続に失敗したアカウントを再試行",
      title__connectionFailed: "接続に失敗したアカウントを再試行",
      title__reauthorize: "再認証が必要",
      subtitle__reauthorize:
        "このアカウントで必要なスコープが更新されました。機能を続けるには再認証してください",
      actionLabel__conectionFailed: "再試行",
      actionLabel__connectionFailed: "再試行",
      actionLabel__reauthorize: "今すぐ認証",
      destructiveActionTitle: "削除",
      destructiveActionSubtitle: "このアカウントの接続を解除",
      destructiveActionAccordionSubtitle: "アカウント接続を解除",
    },
    enterpriseAccountsSection: {
      title: "エンタープライズアカウント",
    },
    passwordSection: {
      title: "パスワード",
      primaryButton__changePassword: "パスワードを変更",
      primaryButton__setPassword: "パスワードを設定",
    },
    mfaSection: {
      title: "2段階認証",
      primaryButton: "2段階認証を追加",
      phoneCode: {
        destructiveActionTitle: "SMS認証を削除",
        destructiveActionSubtitle: "アカウントからSMS認証を削除",
        destructiveActionLabel: "削除",
        title__default: "デフォルトの認証方法",
        title__setDefault: "デフォルトの認証方法に設定",
        subtitle__default: "2段階認証が必要な場合、この認証方法がデフォルトで使用されます。",
        subtitle__setDefault:
          "この認証方法をデフォルトに設定して、2段階認証が必要な場合に使用します。",
        actionLabel__setDefault: "デフォルトに設定",
      },
      backupCodes: {
        headerTitle: "バックアップコード",
        title__regenerate: "バックアップコードを再生成",
        subtitle__regenerate:
          "新しい安全なバックアップコードのセットを取得します。以前のバックアップコードは削除され、使用できなくなります。",
        actionLabel__regenerate: "再生成",
      },
      totp: {
        headerTitle: "認証アプリ",
        title: "認証アプリ",
        subtitle:
          "認証アプリ（Google Authenticator、1Password、Authyなど）を使用して、サインイン時に確認コードを受け取ります。",
        destructiveActionTitle: "削除",
        destructiveActionSubtitle: "アカウントから認証アプリを削除",
        destructiveActionLabel: "削除",
        secret: {
          imageAlt: "QRコード",
          copyButton: "コピー",
        },
      },
    },
    activeDevicesSection: {
      title: "アクティブなデバイス",
      subtitle: "アカウントでアクティブなデバイスのリスト",
      destructiveActionTitle: "サインアウト",
      destructiveActionSubtitle: "このデバイスでアカウントからサインアウト",
      destructiveAction: "サインアウト",
    },
    web3WalletsSection: {
      title: "Web3ウォレット",
      primaryButton: "Web3ウォレットを追加",
      destructiveActionTitle: "削除",
      destructiveActionSubtitle: "このWeb3ウォレットをアカウントから削除",
      destructiveAction: "削除",
    },
    deletionSection: {
      title: "アカウントを削除",
      subtitle: "アカウントとすべての関連データを削除",
      actionDescription: "「アカウントを削除」と入力して続行してください。",
      confirm: "アカウントを削除",
    },
  },
  userButton: {
    action__manageAccount: "アカウント管理",
    action__signOut: "サインアウト",
    action__signOutAll: "すべてのアカウントからサインアウト",
    action__addAccount: "アカウントを追加",
  },
  organizationSwitcher: {
    personalWorkspace: "個人ワークスペース",
    notSelected: "組織が選択されていません",
    action__createOrganization: "組織を作成",
    action__manageOrganization: "組織を管理",
    action__invitationAccept: "参加",
    action__suggestionsAccept: "参加をリクエスト",
    suggestionsAcceptedLabel: "リクエスト保留中",
  },
  impersonationFab: {
    title: "サインイン中: {{identifier}}",
    action__signOut: "サインアウト",
  },
  organizationProfile: {
    badge__unverified: "未確認",
    badge__automaticInvitation: "自動招待",
    badge__automaticSuggestion: "自動提案",
    badge__manualInvitation: "登録なし",
    badge__joinRequest: "参加リクエスト",
    profileSection: {
      title: "組織情報",
      subtitle: "組織情報を管理",
      primaryButton: "更新",
      uploadAction__title: "ロゴ",
      uploadAction__subtitle: "ロゴをアップロード",
      uploadAction__remove: "ロゴを削除",
      displayName__title: "表示名",
      displayName__subtitle: "組織の表示名を設定",
      slug__title: "スラッグ",
      slug__subtitle: "組織のスラッグURLを設定",
      publicMetadata__title: "公開メタデータ",
      publicMetadata__subtitle: "組織の公開メタデータを設定",
      dangerSection__title: "危険",
      dangerSection__leaveOrganization__title: "組織を離れる",
      dangerSection__leaveOrganization__subtitle: "この組織を離れます",
      dangerSection__leaveOrganization__action: "組織を離れる",
      dangerSection__deleteOrganization__title: "組織を削除",
      dangerSection__deleteOrganization__subtitle: "この組織とそのすべてのリソースを削除",
      dangerSection__deleteOrganization__action: "組織を削除",
    },
    invitationsPage: {
      title: "招待状",
      subtitle: "組織に参加するための招待を管理",
      invitationsTab: {
        title: "招待状",
        subtitle: "組織に送信された招待を表示および管理",
        requestsTab__title: "リクエスト",
        requestsTab__subtitle: "組織に参加するためのリクエストを表示および管理",
        table__emptyRow: "表示する招待はありません",
        autoInvitations: {
          headerTitle: "ドメインによる自動招待",
          headerSubtitle: "特定のメールドメインのユーザーが自動的に組織に参加できるようにします",
          primaryButton: "ドメインを追加",
        },
        table__invitedMembers: "招待されたメンバー",
        table__invitedList: "{{value, list}}",
        table__invitedLabel: "招待済み",
      },
      membersTab: {
        title: "メンバー",
        subtitle: "組織のメンバーとその役割を表示および管理",
        table__emptyRow: "表示するメンバーはありません",
        invitedMembersTab: "招待",
        inviteMembersTab__title: "メンバーを招待",
        inviteMembersTab__subtitle: "組織にメンバーを招待",
        searchInput__placeholder: "メールアドレスで検索",
        removeMemberRow__title: "メンバーを削除",
        removeMemberRow__subtitle: "{{identifier}}を組織から削除",
        removeMemberRow__action: "削除",
        editMemberRow__title: "メンバーを編集",
        editMemberRow__subtitle: "{{identifier}}の役割を編集",
        editMemberRow__action: "編集",
      },
    },
  },
  createOrganization: {
    title: "組織を作成",
    subtitle: "組織を作成してチームとコラボレーション",
    formButtonSubmit: "組織を作成",
    invitePage: {
      formButtonReset: "スキップ",
    },
  },
  organizationList: {
    createOrganization: "組織を作成",
    title: "{{applicationName}}のアカウントを選択",
    subtitle: "続行するアカウントを選択してください",
    action__invitationAccept: "参加",
    invitationAcceptedLabel: "参加済み",
    action__suggestionsAccept: "参加をリクエスト",
    suggestionsAcceptedLabel: "リクエスト保留中",
    action__createOrganization: "組織を作成",
  },
  unstable__errors: {
    identification_deletion_failed: "最後の識別子は削除できません。",
    phone_number_exists: "この電話番号は別のアカウントで使用されています。",
    form_identifier_not_found: "",
    captcha_unavailable:
      "ボット検証に失敗したため、サインアップできませんでした。ページを更新して再試行するか、サポートにお問い合わせください。",
    captcha_invalid:
      "セキュリティ検証に失敗したため、サインアップできませんでした。ページを更新して再試行するか、サポートにお問い合わせください。",
    form_password_pwned:
      "このパスワードはデータ漏洩により流出しています。別のパスワードをお試しください。",
    form_username_invalid_length: "ユーザーネームは4文字以上にしてください。",
    form_username_invalid_character: "ユーザーネームには英数字とアンダースコアのみ使用できます。",
    form_param_format_invalid: "{{param}}の形式が正しくありません。",
    form_param_format_invalid__email_address:
      "メールアドレスは有効なメールアドレスである必要があります。",
    form_password_length_too_short: "パスワードは8文字以上にしてください。",
    form_param_nil: "{{param}}を入力してください。",
    form_code_incorrect: "確認コードが正しくありません。",
    form_password_incorrect: "パスワードが正しくありません。",
    form_password_validation_failed: "パスワードが正しくありません。",
    not_allowed_access: "アクセスが許可されていません。",
    form_identifier_exists:
      "このメールアドレスは既に使用されています。別のメールアドレスをお試しください。",
    form_password_not_strong_enough: "パスワードが十分に強力ではありません。",
    form_password_size_in_bytes_exceeded:
      "パスワードのバイト数が最大値を超えています。短くするか、特殊文字を削除してください。",
    passwordComplexity: {
      sentencePrefix: "パスワードには",
      minimumLength: "{{length}}文字以上",
      maximumLength: "{{length}}文字以下",
      requireNumbers: "数字",
      requireLowercase: "小文字",
      requireUppercase: "大文字",
      requireSpecialCharacter: "特殊文字",
    },
    zxcvbn: {
      notEnough: "パスワードが十分に強力ではありません。",
      warnings: {
        straightRow: "キーボードの連続した文字は推測されやすいです。",
        keyPattern: "短いキーボードパターンは推測されやすいです。",
        simpleRepeat: '"aaa"のような繰り返し文字は推測されやすいです。',
        extendedRepeat: '"abcabcabc"のような繰り返しパターンは推測されやすいです。',
        sequences: '"abc"のような一般的な文字列は推測されやすいです。',
        recentYears: "最近の年は推測されやすいです。",
        dates: "日付は推測されやすいです。",
        topTen: "これは非常によく使用されるパスワードです。",
        topHundred: "これはよく使用されるパスワードです。",
        common: "これは一般的に使用されるパスワードです。",
        similarToCommon: "これは一般的に使用されるパスワードに似ています。",
        wordByItself: "単一の単語は推測されやすいです。",
        namesByThemselves: "単一の名前や姓は推測されやすいです。",
        commonNames: "一般的な名前や姓は推測されやすいです。",
        userInputs: "パスワードには個人情報やページ関連の情報を含めないでください。",
        pwned: "このパスワードはインターネット上のデータ漏洩により流出しています。",
      },
      suggestions: {
        l33t: '予測可能な文字置換を避けてください。例："@"を"a"の代わりに使用。',
        reverseWords: "一般的な単語の逆さ綴りを避けてください。",
        allUppercase: "いくつかの文字を大文字にしますが、すべてではありません。",
        capitalization: "最初の文字以外も大文字にしてください。",
        dates: "誕生日や記念日など、自分に関連する日付を避けてください。",
        recentYears: "最近の年を避けてください。",
        associatedYears: "自分に関連する年を避けてください。",
        sequences: '"abc"のような一般的な文字列を避けてください。',
        repeated: "繰り返し文字やパターンを避けてください。",
        longerKeyboardPattern:
          "より長いキーボードパターンを使用し、複数回タイピング方向を変更してください。",
        anotherWord: "より一般的でない単語を追加してください。",
        useWords: "複数の単語を使用しますが、一般的なフレーズは避けてください。",
        noNeed: "記号、数字、大文字を使用せずに強力なパスワードを作成できます。",
        pwned: "このパスワードを他の場所で使用している場合は、変更する必要があります。",
      },
    },
    form_param_max_length_exceeded__name: "名前は256文字以下にしてください。",
    form_param_max_length_exceeded__first_name: "名は256文字以下にしてください。",
    form_param_max_length_exceeded__last_name: "姓は256文字以下にしてください。",
  },
  dates: {
    previous6Days: "過去 {{ date | weekday('ja-JP','long') }} の {{ date | timeString('ja-JP') }}",
    lastDay: "昨日 {{ date | timeString('ja-JP') }}",
    sameDay: "今日 {{ date | timeString('ja-JP') }}",
    nextDay: "明日 {{ date | timeString('ja-JP') }}",
    next6Days: "{{ date | weekday('ja-JP','long') }} の {{ date | timeString('ja-JP') }}",
    numeric: "{{ date | numeric('ja-JP') }}",
  },
};
