name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: 'node_modules'
          key: client-npm-${{ hashFiles('package-lock.json') }}
      - run: npm ci
        if: steps.client-npm-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: backend-npm-cache
        with:
          path: 'backend/node_modules'
          key: backend-npm-${{ hashFiles('backend/package-lock.json') }}
      - run: |
          cd backend
          npm install
        if: steps.backend-npm-cache.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: npm run typecheck
